config:
  api:
    azure_translate:
      key: "1234"
      endpoint: "https://cognitiveservices.azure.com/"
  initial:
    account:
      id: 1234567
      api_id: 1234567
      api_hash: "1234567"
      first_name: "Bob"
      last_name: "Smith"
      phone: '+11235556789'
      username: 'informer'
    channel:
      use_initial: false
      name: "informer"
      id: 1234567
      url: "https://t.me/joinchat/1234567"
      is_private: True
  crawling:
    enabled: true
  database:
    sql:
      database: "informer"
      username: "root"
      password: "root"
      hostname: "localhost"
      port: 3306
    elastic_search:
      connection_uri: "localhost:9200"
  notification:
    telegram:
      enabled: false
      channel_id: 1234567
    google_sheets:
      enabled: false
      credentials_path: "credentials/gcloud_api.json"
      sheet_name: "Informer Notifications"
    sql:
      enabled: false
    json:
      enabled: false
    elastic_search:
      enabled: false